name: Build project

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      production:
        type: boolean
        default: false
        description: Whether to deploy to production or preview

    secrets:
      GRADLE_ENCRYPTION_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIST_PATH: "composeApp/build/dist/wasmJs/${{ (inputs.production == true && 'production') || 'development' }}Executable/"

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Prepare Java & Gradle
        uses: ./.github/actions/prepare-gradle
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-overwrite-existing: 'true'

      - name: Production build with Gradle
        if: inputs.production == true
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Development build with Gradle
        if: inputs.production == false
        run: ./gradlew :composeApp:wasmJsBrowserDevelopmentExecutableDistribution

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: web-${{ (inputs.production == true && 'release') || 'debug' }}
          path: ${{ env.DIST_PATH }}
