name: Deploy

concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: 'web-*'
          path: artifacts

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          command: pages deploy "./artifacts/" --project-name=stashydev --branch=${{ github.ref_name }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
